#!/usr/bin/env groovy
library 'kibana-pipeline-library'

pipeline {
    agent { label 'docker && tests-xl-highmem' }
    environment {
        STACK_VERSION = "7.11.0-SNAPSHOT"
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    echo "STACK_VERSION = ${STACK_VERSION}"
                '''
            }
        }

        stage ('Build') {
            steps {
              withVaultSecret(secret: 'secret/kibana-issues/dev/cloud-staging-api-key', secret_field: 'value', variable_name: 'API_KEY')  {
                sh '''
                    cd kibana-load-testing
                    export cloudDeploy=${STACK_VERSION}
                    mvn clean -q -Dmaven.test.failure.ignore=true compile
                    mvn gatling:test -q -Dgatling.simulationClass=org.kibanaLoadTest.simulation.DemoJourney
                '''
              }

            }
            post {
                success {
                  withVaultSecret(secret: 'secret/kibana-issues/prod/coverage/elasticsearch', secret_field: 'host', variable_name: 'HOST_FROM_VAULT') {
                    withVaultSecret(secret: 'secret/kibana-issues/prod/coverage/elasticsearch', secret_field: 'username', variable_name: 'USER_FROM_VAULT') {
                      withVaultSecret(secret: 'secret/kibana-issues/prod/coverage/elasticsearch', secret_field: 'password', variable_name: 'PASS_FROM_VAULT') {
                        sh '''
                          cd kibana-load-testing
                          mvn exec:java -Dexec.mainClass=org.kibanaLoadTest.ingest.Main -Dexec.classpathScope=test -Dexec.cleanupDaemonThreads=false
                        '''
                      }
                    }
                  }
                }
            }
        }
    }
}