pipeline {
    agent { label 'docker && tests-xl-highmem' }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
              withVaultSecret(secret: vaultSecret, secret_field: 'cloud_staging_api_key', variable_name: 'API_KEY')  {
                sh '''
                    export API_KEY=${API_KEY}
                    export deployConfig=config/deploy/7.9.3.conf
                    mvn -Dmaven.test.failure.ignore=true install
                    mvn gatling:test -Dgatling.simulationClass=org.kibanaLoadTest.simulation.DemoJourney
                '''
              }

            }
            post {
                success {
                   sh '''
                   echo "Report ingestion will be added later"
                '''
                }
            }
        }
    }
}